trigger:
- master

pool:
  vmImage: ubuntu-latest

parameters:
  - name: resourcegroup
    type: object
    default:
    - rg-ando-01
    - rg-hibi-annotation-01

steps:
- ${{ each value in parameters.resourcegroup }}:
  - task: AzureCLI@2
    displayName: Close VM using az cli
    inputs:
      azureSubscription: 'YOUR_SUBSCRIPTION_HERE'
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: 'az resource list --resource-group ${{ value }}  --output table'

